services:
  mysqldb:   
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ruchi    
      MYSQL_DATABASE: grocery_db 
    ports: 
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springboot-mysql-net

  backend:
    image : ruchithavemula11/groce-backend:latest 
    container_name: grocebackend
    ports:
      - "30060:2080"
    depends_on:
      - mysqldb
    restart: on-failure
    networks:
      - springboot-mysql-net

  frontend:
    image: ruchithavemula11/groce-frontend:latest
    container_name: grocefrontend
    ports:
      - "30070:80"
    depends_on:
      - backend
    restart: on-failure
    networks:
      - springboot-mysql-net

volumes:
  mysql_data:

networks:
  springboot-mysql-net:
